---
abstract: 'Memcached Runner For Tests'
author:
  - 'Kazuho Oku wrote Test::mysqld, which I shamelessly stole from.'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Memcached
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Accessor::Lite: 0
  Cwd: 0
  File::Temp: 0
  IO::Socket::INET: 0
  Time::HiRes: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.00003
